version: '3.3'

services:
   db:
     image: mysql:latest
     volumes:
       - ./wordpress.sql:/docker-entrypoint-initdb.d/init.sql # prepopulate database
       - db_data:/var/lib/mysql # persist database data inside docker storage
     restart: "no"
     env_file:
      - .env
     environment:
      DOCKER_COMPOSE_YML_LOCATION: ${PWD}
     container_name: mysql_db

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     restart: "no"
     ports:
       - "9083:80"
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       DOCKER_COMPOSE_YML_LOCATION: ${PWD}
     container_name: mysql_phpmyadmin

   wordpress:
     depends_on:
       - db
     image: wordpress:php7.4
     ports:
       - "9084:80"
     restart: "no"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
       DOCKER_COMPOSE_YML_LOCATION: ${PWD}
     volumes:
       - ./html:/var/www/html
     container_name: wordpress

volumes:
    db_data: {}
